### ISSUE TITLE
ModuleNotFoundError: No module named 'six.moves'

### ISSUE THREAD

**Issue by eyalzek** [GoogleCloudPlatform/gcpdiag#103]
Docker image tag 0.77 is failing with the error in the title:
```
$ gcpdiag lint --project  <PROJECT_ID>
Trying to pull us-docker.pkg.dev/gcpdiag-dist/release/gcpdiag:0.77...
Getting image source signatures
Copying blob 8fc0ca9db0b0 done   | 
Copying blob a26fa095e3c8 done   | 
Copying blob 99eef00f51a7 done   | 
Copying blob 6a6e32e60546 done   | 
Copying blob ff65ddf9395b done   | 
Copying blob 0839cacc4efd done   | 
Copying blob 839fca60997c done   | 
Copying blob 68cd88696cf1 done   | 
Copying blob c52d7fdcc910 done   | 
Copying blob 5b26d6cd77ec done   | 
Copying blob d9900443c7b7 done   | 
Copying blob 9f5e323d68f0 done   | 
Copying config 24a85ada98 done   | 
Writing manifest to image destination
Traceback (most recent call last):
  File "/opt/gcpdiag/bin/gcpdiag", line 23, in <module>
    from gcpdiag.lint import command as lint_command
  File "/opt/gcpdiag/gcpdiag/lint/__init__.py", line 42, in <module>
    from gcpdiag.queries import logs
  File "/opt/gcpdiag/gcpdiag/queries/logs.py", line 47, in <module>
    import dateutil.parser
  File "/opt/gcpdiag/.venv/lib/python3.12/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/opt/gcpdiag/.venv/lib/python3.12/site-packages/dateutil/parser/_parser.py", line 50, in <module>
    from .. import tz
  File "/opt/gcpdiag/.venv/lib/python3.12/site-packages/dateutil/__init__.py", line 16, in __getattr__
    return importlib.import_module("." + name, __name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/gcpdiag/.venv/lib/python3.12/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/opt/gcpdiag/.venv/lib/python3.12/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
ModuleNotFoundError: No module named 'six.moves'
```

**Comment by ebenezergraham** [comment]
Thanks for reporting the issue. Please try again reverted to 0.76

**Comment by ebenezergraham** [comment]
the application has been migrated to python 3.12 in  [v0.78](https://github.com/GoogleCloudPlatform/gcpdiag/releases/tag/v0.78) which should solve this issue.
