### ISSUE TITLE
[WARNING] Encountered 403 Forbidden with reason "PERMISSION_DENIED"

### ISSUE THREAD

**Issue by kevin-shelaga** [GoogleCloudPlatform/gcpdiag#14]
Crash when Identity and Access Management (IAM) API is not enabled.

```sh
 OS Config service account has the required permissions.
[WARNING] Encountered 403 Forbidden with reason "PERMISSION_DENIED"
   ... fetching IAM roles: projects/my-projectTraceback (most recent call last):
  File "/opt/gcpdiag/gcpdiag/queries/iam.py", line 221, in get_project_policy
   ... executing monitoring query (project: my-project)    return ProjectPolicy(project_id)
  File "/opt/gcpdiag/gcpdiag/queries/iam.py", line 212, in __init__
    self._custom_roles = _fetch_roles('projects/' + self._project_id,
  File "/opt/gcpdiag/gcpdiag/queries/iam.py", line 58, in _fetch_roles
    response = request.execute(num_retries=config.API_RETRIES)
  File "/opt/gcpdiag/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/gcpdiag/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://iam.googleapis.com/v1/projects/my-project/roles?view=FULL&alt=json returned "Identity and Access Management (IAM) API has not been used in project 1234567890 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=1234567890 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=1234567890'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/1234567890', 'service': 'iam.googleapis.com'}}]">

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/gcpdiag/bin/gcpdiag", line 65, in <module>
    main(sys.argv)
  File "/opt/gcpdiag/bin/gcpdiag", line 43, in main
    lint_command.run(argv)
  File "/opt/gcpdiag/gcpdiag/lint/command.py", line 194, in run
    exit_code = repo.run_rules(context, report, include_patterns,
  File "/opt/gcpdiag/gcpdiag/lint/__init__.py", line 351, in run_rules
    rule.prefetch_rule_future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/gcpdiag/gcpdiag/lint/gce/err_2021_002_osconfig_perm.py", line 34, in prefetch_rule
    iam.get_project_policy(pid)
  File "/opt/gcpdiag/gcpdiag/caching.py", line 145, in _cached_api_call_wrapper
    return lru_cached_func(*args, **kwargs)
  File "/opt/gcpdiag/gcpdiag/queries/iam.py", line 223, in get_project_policy
    raise utils.GcpApiError(err) from err
gcpdiag.utils.GcpApiError: can't fetch data, reason: Identity and Access Management (IAM) API has not been used in project 1234567890 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=1234567890 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
[WARNING] Encountered 403 Forbidden with reason "PERMISSION_DENIED"
[WARNING] Encountered 403 Forbidden with reason "PERMISSION_DENIED"
[WARNING] Encountered 403 Forbidden with reason "PERMISSION_DENIED"
   ... still fetching logs (project: my-project, resource type: k8s_node, max wait: 112s)%
```

**Comment by schweikert** [comment]
Thanks for reporting this! This issue should be fixed in the next release.
