### ISSUE TITLE
Error: sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by pbiggar** [GoogleCloudPlatform/gcpdiag#29]
Hi, tried using this for the first time on ubuntu 20.04, got this error.

```
$ curl https://gcpdiag.dev/gcpdiag.sh >gcpdiag
$ chmod +x gcpdiag
$ ./gcpdiag lint --project=MYPROJECT
Unable to find image 'us-docker.pkg.dev/gcpdiag-dist/release/gcpdiag:0.55' locally
0.55: Pulling from gcpdiag-dist/release/gcpdiag
<DOCKER PULL STUFF>
Digest: sha256:0b5fcc0fd3e2f1b822cec492b0128f7e1df5173c19990570ee072c80cf6164c4
Status: Downloaded newer image for us-docker.pkg.dev/gcpdiag-dist/release/gcpdiag:0.55
gcpdiag 🩺 0.55

Starting lint inspection (project: MYPROJECT)...

Traceback (most recent call last):
  File "/opt/gcpdiag/bin/gcpdiag", line 64, in <module>
    main(sys.argv)
  File "/opt/gcpdiag/bin/gcpdiag", line 42, in main
    lint_command.run(argv)
  File "/opt/gcpdiag/gcpdiag/lint/command.py", line 237, in run
    apis.verify_access(context.project_id)
  File "/opt/gcpdiag/gcpdiag/queries/apis.py", line 253, in verify_access
    if not is_enabled(project_id, 'cloudresourcemanager'):
  File "/opt/gcpdiag/gcpdiag/queries/apis.py", line 246, in is_enabled
    return f'{service_name}.googleapis.com' in _list_apis(project_id)
  File "/opt/gcpdiag/gcpdiag/caching.py", line 145, in _cached_api_call_wrapper
    return lru_cached_func(*args, **kwargs)
  File "/opt/gcpdiag/gcpdiag/queries/apis.py", line 230, in _list_apis
    serviceusage = get_api('serviceusage', 'v1', project_id)
  File "/opt/gcpdiag/gcpdiag/caching.py", line 145, in _cached_api_call_wrapper
    return lru_cached_func(*args, **kwargs)
  File "/opt/gcpdiag/gcpdiag/queries/apis.py", line 197, in get_api
    credentials = _get_credentials()
  File "/opt/gcpdiag/gcpdiag/queries/apis.py", line 160, in _get_credentials
    return _get_credentials_oauth()
  File "/opt/gcpdiag/gcpdiag/queries/apis.py", line 119, in _get_credentials_oauth
    with caching.get_cache() as diskcache:
  File "/opt/gcpdiag/gcpdiag/caching.py", line 60, in get_cache
    _cache = diskcache.Cache(config.CACHE_DIR, tag_index=True)
  File "/opt/gcpdiag/.venv/lib/python3.9/site-packages/diskcache/core.py", line 456, in __init__
    sql = self._sql_retry
  File "/opt/gcpdiag/.venv/lib/python3.9/site-packages/diskcache/core.py", line 652, in _sql_retry
    sql = self._sql
  File "/opt/gcpdiag/.venv/lib/python3.9/site-packages/diskcache/core.py", line 648, in _sql
    return self._con.execute
  File "/opt/gcpdiag/.venv/lib/python3.9/site-packages/diskcache/core.py", line 623, in _con
    con = self._local.con = sqlite3.connect(
sqlite3.OperationalError: unable to open database file
```

**Comment by schweikert** [comment]
That's interesting and something I didn't see before. The wrapper is adding the following arguments when running gcpdiag: `-v "$HOME/.cache/gcpdiag-dockerized:$HOME/.cache/gcpdiag"` and is storing data in a sqlite database under that directory (`~/.cache/gcpdiag-dockerized` outside of the docker container). It looks like there is a permission issue that prevents gcpdiag from writing there.

Are you using docker or podman (the wrapper will try first to use docker, and use podman otherwise if installed)?

Can you verify the permissions of the directory in ~/.cache ? It looks like this for me:

```
$ ls -ld ~/.cache ~/.cache/gcpdiag-dockerized ~/.cache/gcpdiag-dockerized/cache.db
drwxr-xr-x 51 dwes primarygroup  4096 Apr 21 14:51 /usr/local/google/home/dwes/.cache
drwxr-x--- 13 dwes primarygroup  4096 Apr 22 10:41 /usr/local/google/home/dwes/.cache/gcpdiag-dockerized
-rw-r--r--  1 dwes primarygroup 36864 Apr 22 10:41 /usr/local/google/home/dwes/.cache/gcpdiag-dockerized/cache.db
```

**Comment by pbiggar** [comment]
I'm using docker.

```
$ ls -ld ~/.cache ~/.cache/gcpdiag-dockerized ~/.cache/gcpdiag-dockerized/cache.db
ls: cannot access '/home/dark/.cache/gcpdiag-dockerized': No such file or directory
ls: cannot access '/home/dark/.cache/gcpdiag-dockerized/cache.db': No such file or directory
drwxr-xr-x 1 dark dark 4096 May 28 19:16 /home/dark/.cache
```

Hmm, this is probably caused because I tried to the command from within a docker container. The `~/.cache` directory is in the container and not accessible from the host.

Alternatively, it could be related to uids. Here's the id on the container from which I'm calling the script:

```
$ id
uid=1000(dark) gid=1000(dark) groups=1000(dark),27(sudo)
```

and from my host machine:

```
 $ id
uid=501(paulbiggar) gid=20(staff) groups=20(staff),101(access_bpf),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),702(com.apple.sharepoint.group.2),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)
```

**Comment by schweikert** [comment]
The [gcpdiag.sh](https://gcpdiag.dev/gcpdiag.sh) script is supposed to create those directories and also set the correct user. Not sure what is happening in your case, but this seems to be more like a problem specific to you and not a bug. I will close the github issue, but feel free to reopen if you find an issue with the wrapper or the docker image.
