### ISSUE TITLE
[gcs/BP/2022_001] KeyError: 'iamConfiguration' 

### ISSUE THREAD

**Issue by alainknaebel** [GoogleCloudPlatform/gcpdiag#41]
gcpdiag version: 0.55

It seems that some buckets does not have a `iamConfiguration` field which is making gcpdiag crashing with an exception (seems to happen only on old buckets)

Ideally, gcpdiag need to test if the key `iamConfiguration` is defined or not and if the key is not defined it will returned a default value

python exception:
```
Traceback (most recent call last):
  File "/opt/gcpdiag/bin/gcpdiag", line 64, in <module>
    main(sys.argv)
  File "/opt/gcpdiag/bin/gcpdiag", line 42, in main
    lint_command.run(argv)
  File "/opt/gcpdiag/gcpdiag/lint/command.py", line 240, in run
    exit_code = repo.run_rules(context, report, include_patterns,
  File "/opt/gcpdiag/gcpdiag/lint/__init__.py", line 367, in run_rules
    rule.run_rule_f(context, rule_report)
  File "/opt/gcpdiag/gcpdiag/lint/gcs/bp_2022_001_bucket_access_uniform.py", line 37, in run_rule
    elif b.is_uniform_access():
  File "/opt/gcpdiag/gcpdiag/queries/gcs.py", line 48, in is_uniform_access
    return self._resource_data['iamConfiguration']['uniformBucketLevelAccess'][
KeyError: 'iamConfiguration'
```

Bucket json informations returned by the api for the exception:
```
{
  "kind": "storage#bucket",
  "selfLink": "https://www.googleapis.com/storage/v1/b/mybucket",
  "id": "mybucket",
  "name": "mybucket",
  "projectNumber": "00000000000",
  "metageneration": "9",
  "location": "US",
  "storageClass": "STANDARD",
  "etag": "CAk=",
  "timeCreated": "2016-07-12T15:05:45.473Z",
  "updated": "2022-06-22T10:25:28.219Z",
  "locationType": "multi-region",
  "rpo": "DEFAULT"
}
```
Working bucket json informations returned by the api:
```
{
  "kind": "storage#bucket",
  "selfLink": "https://www.googleapis.com/storage/v1/b/mybucket",
  "id": "mybucket",
  "name": "mybucket",
  "projectNumber": "00000000000",
  "metageneration": "3",
  "location": "EU",
  "storageClass": "STANDARD",
  "etag": "CAM=",
  "defaultEventBasedHold": false,
  "timeCreated": "2021-04-06T10:19:45.615Z",
  "updated": "2021-04-06T13:10:55.598Z",
  "iamConfiguration": {
    "bucketPolicyOnly": {
      "enabled": false
    },
    "uniformBucketLevelAccess": {
      "enabled": false
    },
    "publicAccessPrevention": "inherited"
  },
  "locationType": "multi-region",
  "satisfiesPZS": false,
  "rpo": "DEFAULT"
}
```

**Comment by dawidmalina** [comment]
Hi @alainknaebel thank you for rising this issue and full list of api responses. Indeed problem is with old bucket definition that does not contains `iamConfiguration` property and gcpdiag should handle this. Fix for this problem will be delivered with next release.
