### ISSUE TITLE
Error for rule dataproc/warn_2022_002_job_throttling_rate_limit

### ISSUE THREAD

**Issue by abhigupta1207** [GoogleCloudPlatform/gcpdiag#57]
Traceback (most recent call last):
  File "/opt/gcpdiag/bin/gcpdiag", line 70, in <module>
    main(sys.argv)
  File "/opt/gcpdiag/bin/gcpdiag", line 43, in main
    lint_command.run(argv)
  File "/opt/gcpdiag/gcpdiag/lint/command.py", line 290, in run
    repo.run_rules(context)
  File "/opt/gcpdiag/gcpdiag/lint/__init__.py", line 495, in run_rules
    self.execution_strategy.run_rules(context, self.result, rules_to_run)
  File "/opt/gcpdiag/gcpdiag/lint/__init__.py", line 575, in run_rules
    rule.run_rule_f(context, rule_report)
  File "/opt/gcpdiag/gcpdiag/lint/dataproc/warn_2022_002_job_throttling_rate_limit.py", line 73, in run_rule
    clusters_with_throttling = get_clusters_having_relevant_log_entries(context)
  File "/opt/gcpdiag/gcpdiag/lint/dataproc/warn_2022_002_job_throttling_rate_limit.py", line 61, in get_clusters_having_relevant_log_entries
    return {
  File "/opt/gcpdiag/gcpdiag/lint/dataproc/warn_2022_002_job_throttling_rate_limit.py", line 62, in <setcomp>
    e.cluster_name
AttributeError: 'dict' object has no attribute 'cluster_name'

**Comment by kaushik853** [comment]
How this is an issue, it runs ok in the project shell. Can you please elaborate a little more on this?

**Comment by abhigupta1207** [comment]
@kaushik853 please run it in a project where dataproc cluster is deployed
